name: schat_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0
  

# Add regular dependencies here.
dependencies:
  grpc: ^5.1.0
  protobuf: ^6.0.0
  protoc_plugin: ^25.0.0
  stormberry: ^0.18.0
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.6
  minio: ^3.5.0
  uuid: ^4.0.0
  xor_dart: ^1.0.2



  
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.8
